DROP TABLE IF EXISTS PRICES;

-- Create the PRICES table
CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP(6) NOT NULL,
    END_DATE TIMESTAMP(6) NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE FLOAT(53) NOT NULL,
    CURR VARCHAR(3) NOT NULL
);

-- Add an index for performance optimization
CREATE INDEX IDX_PRICES_DATE
ON PRICES (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY);
